apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          # Service account with Docker Hub credentials
          serviceAccountName: build-bot
          source:
            git:
              url: https://github.com/davidcurrie/devoxx-uk-2019.git
              revision: master
          template:
            name: kaniko
            arguments:
              - name: IMAGE
                value: docker.io/dcurrie/helloworld-go:latest
          timeout: 10m
      revisionTemplate:
        spec:
          container:
            image: docker.io/dcurrie/helloworld-go
            env:
              - name: VERSION
                value: "v4"