apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    build.knative.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
data:
  username: xxx # base64 encoded Docker Hub username
  password: yyy # base64 encoded Docker Hub password